name: Build OpenWrt SNAPSHOT APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      

    - name: Update and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang libc6-dev-i386 libc6-x32 libc6-dev-x32 \
          gcc-multilib g++-multilib \
          python3 python3-venv python3-pip python3-setuptools python3-distutils-extra \
          curl wget tar xz-utils git

    - name: Install static apk-tools
      run: |
        APK_VER="2.14.3-r0"
        APK_URL="https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/apk-tools-static-$APK_VER.apk"
        curl -sSL $APK_URL -o apk-tools-static.apk
        mkdir -p apk-tools-static
        tar -xzf apk-tools-static.apk -C apk-tools-static
        sudo cp apk-tools-static/sbin/apk.static /usr/local/bin/apk
        chmod +x /usr/local/bin/apk

    - name: Verify environment
      run: |
        python3 --version
        apk --version

    - name: Clone OpenWrt SNAPSHOT
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Prepare OpenWrt build
      run: |
        cd openwrt
        make defconfig

    - name: Build OpenWrt APK packages
      run: |
        cd openwrt
        # 如果你要单独打包特定插件，可以替换下面的 target
        make package/<your-package>/compile V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-apk
        path: openwrt/bin/packages
